# Generated by Django 4.2.1 on 2023-05-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('status', models.TextField()),
                ('imported_t', models.TextField()),
                ('creator', models.TextField()),
                ('created_t', models.TextField()),
                ('last_modified_t', models.TextField()),
                ('url', models.TextField()),
                ('product_name', models.TextField()),
                ('quantity', models.TextField()),
                ('brands', models.TextField()),
                ('categories', models.TextField()),
                ('labels', models.TextField()),
                ('cities', models.TextField()),
                ('purchase_places', models.TextField()),
                ('stores', models.TextField()),
                ('ingredients_text', models.TextField()),
                ('traces', models.TextField()),
                ('serving_size', models.TextField()),
                ('serving_quantity', models.TextField()),
                ('nutriscore_score', models.TextField()),
                ('nutriscore_grade', models.TextField()),
                ('main_category', models.TextField()),
                ('image_url', models.TextField()),
            ],
            options={
                'db_table': 'products',
                'managed': True,
            },
        ),
    ]
